---
galaxy_info:
  author: librato
  description: Install and configure the Librato Agent
  company: Librato
  license: MIT
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
      - 6
      - 7
  - name: Fedora
    versions:
      - 23
  - name: Ubuntu
    versions:
      - trusty
      - precise
      - xenial
      - wily
      - vivid
  - name: Debian
    versions:
      - jessie
      - wheezy
  galaxy_tags:
    - librato
    - collectd
    - monitoring
