---
- hosts: all
  vars:
  become: true
  # gather_facts needs to be false only for the bootstrap installation of python.
  # There may be other reasons to set gather_facts to false as well.
  # Having to do with multiple playbooks.
  gather_facts: false
  pre_tasks:
    # install python only if ping fails
    - name: Try ping first to see if a python already exists
      ping:
      ignore_errors: true
      register: chkping
    - name: Bootstrap installation of python
      raw: apt-get -y install python
      when: chkping is failed
    - name: Gather facts anyways
      action: setup
  tasks:
    # Keys first, then repos, then the dist-upgrade.
    - name: Add repository for ansible
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
    - name: Do a dist-upgrade
      apt:
        upgrade: dist
        update_cache: yes
    - name: Install the lastest versions of listed packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - python3
        - ansible
        - unzip                 # for ansible unarchive module
        - curl
        - git
        - screen
        - emacs
        - openjdk-8-jdk         # For Clojure
        - rlwrap                # For clj
        - htop                  # To view processes
    - name: Purge installed apps
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - ubuntu-web-launchers  # to remove Amazon icon from launcher
    # Unfortunately, the apt version of lein is quite old, so install in /usr/local/bin
    - name: Set up Leiningen
      import_role:
        name: leiningen
    # Too bad we cannot use the alternatives module
    # as it would require listing each java command.
    - name: Check if jdk8 is default
      command: update-alternatives --display java
      register: chkjava
      changed_when: false
      check_mode: false
    - name: Choose jdk8 as default for Clojure
      command: update-java-alternatives --set java-1.8.0-openjdk-amd64
      when: chkjava.stdout.find('link currently points to /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java') == -1
    # Clean up
    - name: Remove unneeded apt stuff
      apt:
        autoremove: yes
    # Firewall settings
    - name: Set firewall settings to allow ssh, http/s
      import_role:
        name: firewall
    #########
    # Now set up the users
    - name: Set up plexus
      import_role:
        name: setup_user
      vars:
        username: plexus
        full_name: Arne Brasseur
        github_username: plexus
    - name: Set up lispyclouds
      import_role:
        name: setup_user
      vars:
        username: lispyclouds
        full_name: Rahul De
        github_username: lispyclouds
    - name: Set up victorb
      import_role:
        name: setup_user
      vars:
        username: victorb
        full_name: Victor Bjelkholm
        github_username: victorb
    - name: Set up dorab
      import_role:
        name: setup_user
      vars:
        username: dorab
        full_name: Dorab Patel
        github_username: bombaywalla
    # TODO: might want to remove some users such as vagrant or ubuntu??
    # Harden sshd. Note: This MUST come after at least one sudoable user having a pubkey login.
    - name: Harden sshd
      import_role:
        name: harden_sshd
