librato_email: ''
librato_token: ''
librato_repo_url: 'https://packagecloud.io/librato/'
librato_repo_base: 'librato-collectd'
librato_deb_version: '5.5.0-librato51.251'
librato_rh_version: '5.5.0_librato51.251'
librato_config_base: '/opt/collectd/etc'
librato_plugin_config_path: '/opt/collectd/etc/collectd.conf.d'
librato_fqdn_lookup: true
librato_interval: 60
librato_default_plugins: ['cpu', 'df', 'disk', 'swap', 'memory', 'load']
librato_enabled_plugins: []

librato_logging_use_log_file: true
librato_logging_use_syslog: false
librato_logging_use_logstash: false
librato_logging_log_file_log_level: 'info'
librato_logging_log_file_filename: '/opt/collectd/var/log/collectd.log'
librato_logging_log_file_timestamp: true
librato_logging_log_file_print_severity: false
librato_logging_syslog_log_level: 'info'
librato_logging_logstash_log_level: 'info'
librato_logging_logstash_filename: '/opt/collectd/var/log/collectd.json.log'

librato_apache_protocol: 'http'
librato_apache_host: 'localhost'
librato_apache_path: '/server-status'

librato_nginx_protocol: 'http'
librato_nginx_host: 'localhost'
librato_nginx_path: '/basic_status'

librato_nginx_plus_protocol: 'http'
librato_nginx_plus_host: 'localhost'
librato_nginx_plus_path: '/status'
librato_nginx_plus_verbose: false

librato_memcached_host: 'localhost'
librato_memcached_port: '11211'

librato_elasticsearch_protocol: 'http'
librato_elasticsearch_host: 'localhost'
librato_elasticsearch_port: '9200'
librato_elasticsearch_verbose: true

librato_mongodb_host: 'localhost'
librato_mongodb_port: '27017'
librato_mongodb_databases: []
librato_mongodb_name: 'mongodb'

librato_zookeeper_host: 'localhost'
librato_zookeeper_port: '2181'

librato_haproxy_socket_file: '/run/haproxy/admin.sock'
librato_haproxy_proxies: ['server', 'frontend', 'backend']

librato_redis_host: 'localhost'
librato_redis_port: '6379'
librato_redis_timeout: '2000'

librato_mysql_databases: []

librato_postgresql_databases: []
librato_postgresql_socket_file: '/var/run/postgresql'
librato_postgresql_user: 'postgresql'

librato_docker_protocol: 'http'
librato_docker_host: 'localhost'
librato_docker_port: '2735'

librato_jvm_host: 'localhost'
librato_jvm_service_url: 'service:jmx:rmi:///jndi/rmi://localhost:17264/jmxrmi'
librato_jvm_mbeans: []
