---
- name: Install rtmbot
  git:
    repo: "https://github.com/clojureverse/rtmbot.git"
    dest: "/var/rtmbot"

- name: Install rtmbot.conf
  template:
    src: templates/rtmbot.conf.j2
    dest: "/var/rtmbot/rtmbot.conf"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0644
  tags: rtmbot

- name: Upload rtmbot Systemd startup script
  template:
    src: templates/rtmbot.service.j2
    dest: "/etc/systemd/system/rtmbot.service"
  tags: rtmbot

- name: Start the rtmbot
  service:
    name: rtmbot
    state: started
    enabled: yes
  tags: rtmbot
