---
- name: Install the app configuration
  template:
    src: templates/config.edn
    dest: "{{ clojure_app_home_dir }}/config.edn"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
  tags: app-config

- name: Create SSH public key
  copy:
    content: "{{ clojure_app_ssh_id_rsa_pub }}"
    dest: "{{ clojure_app_home_dir }}/.ssh/id_rsa.pub"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0644

- name: Create SSH private key
  copy:
    content: "{{ clojure_app_ssh_id_rsa }}"
    dest: "{{ clojure_app_home_dir }}/.ssh/id_rsa"
    owner: "{{ clojure_app_user }}"
    group: "{{ clojure_app_user }}"
    mode: 0600

- name: Clone the Clojurians log app
  become: yes
  become_user: "{{ clojure_app_user }}"
  git:
    repo: "https://github.com/clojureverse/clojurians-log-app.git"
    dest: "/tmp/slack-archiver-tmp"
    version: "{{ slack_archiver_git_branch }}"

- name: Push master to the bare repo
  command: "git push {{ clojure_app_repo_dir }} master:master"
  become: yes
  become_user: "{{ clojure_app_user }}"
  args:
    chdir: "/tmp/slack-archiver-tmp"
    creates: "{{ clojure_app_repo_dir }}/refs/heads/master"

- name: Check out existing logs
  become: yes
  become_user: "{{ clojure_app_user }}"
  become_method: sudo
  git:
    repo: "{{ slack_archiver_logs_repo_url }}"
    dest: "{{ clojure_app_home_dir }}/logs"
    accept_hostkey: yes
    key_file: "{{ clojure_app_home_dir }}/.ssh/id_rsa"
  tags: git-checkout
  when: slack_archiver_auto_load_logs|bool

- name: Import logs
  command: "nc -N localhost {{ clojure_socket_repl_port }} < {{ clojure_app_app_dir }}/repl/production_import.clj > {{ clojure_app_app_dir }}/initial_import.txt"
  when: slack_archiver_auto_load_logs|bool
  args:
    creates: "{{ clojure_app_app_dir }}/initial_import.txt"
